name: Sync TiDB Branches to GitHub Pages

on:
  workflow_dispatch:  # Allows manual triggering of the workflow
  schedule:
    - cron: '0 2 * * *'  # Automatically run the workflow every day at 2 AM UTC+2

jobs:
  sync-branches:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the source repository (pingcap/tidb)
    - name: Checkout pingcap/tidb repository
      uses: actions/checkout@v3
      with:
        repository: pingcap/tidb
        token: ${{ secrets.GITHUB_TOKEN }}

    # Step 2: Get all branches and their creation times
    - name: Get all branches and their creation times
      run: |
        # Get all remote branch names
        branches=$(git branch -r | grep "origin/" | sed 's/origin\///')
        
        # Get creation time of each branch (first commit date)
        branch_data=()
        for branch in $branches; do
          # Get creation time for each branch (first commit date)
          create_time=$(git log --reverse --pretty=format:"%ad" --date=iso --max-count=1 "origin/$branch")
          branch_data+=("{\"branch\": \"$branch\", \"created_at\": \"$create_time\"}")
        done

        # Create JSON file
        echo "[" > branches.json
        echo "${branch_data[*]}" | sed 's/}/},/g' | sed 's/,$//' >> branches.json
        echo "]" >> branches.json

    # Step 3: Push to GitHub Pages repository
    - name: Push to GitHub Pages repository
      uses: git@github.com:AricSu/aricsu.github.io.git
      with:
        repository: AricSu/aricsu.github.io
        token: ${{ secrets.GITHUB_TOKEN }}

    # Step 4: Commit and push the branches JSON to the target repository
    - name: Commit and push branches.json to pages
      run: |
        # Checkout the target GitHub Pages repository
        git clone https://github.com/AricSu/aricsu.github.io.git pages
        cd pages

        # Create the necessary directory and copy the JSON file
        mkdir -p docs/public/tihc/api
        cp ../branches.json docs/public/tihc/api/branches.json

        # Commit and push the changes to the pages repository
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add docs/public/tihc/api/branches.json
        git commit -m "Update TiDB branches with creation times"
        git push origin main
