name: Fetch all branches and creation time

on:
  workflow_dispatch:

jobs:
  fetch-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout this repository
        uses: actions/checkout@v3

      - name: Configure Git identity
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Clone and fetch all upstream branches
        run: |
          git clone https://github.com/pingcap/tidb.git tidb-upstream
          cd tidb-upstream
          git fetch origin "+refs/heads/*:refs/remotes/origin/*"

      - name: Extract branch creation times
        run: |
          cd tidb-upstream

          branches=$(git for-each-ref --format='%(refname:short)' refs/remotes/origin/ | grep -v 'HEAD' | sed 's|^origin/||')

          branch_data=()
          for branch in $branches; do
            create_time=$(git log --reverse --pretty=format:"%ad" --date=iso --max-count=1 "origin/$branch")
            branch_data+=("{\"branch\": \"$branch\", \"created_at\": \"$create_time\"}")
          done

          echo "[" > branches.json
          printf "%s\n" "${branch_data[@]}" | sed '$!s/$/,/' >> branches.json
          echo "]" >> branches.json

      - name: Push JSON to VitePress repo
        env:
          PUSH_TOKEN: ${{ secrets.TIDB_PUSH_TOKEN }}
        run: |
          git clone https://x-access-token:${PUSH_TOKEN}@github.com/AricSu/aricsu.github.io.git site-repo
          mkdir -p site-repo/docs/public/tihc/api
          cp tidb-upstream/branches.json site-repo/docs/public/tihc/api/branches.json

          cd site-repo
          git add docs/public/tihc/api/branches.json
          git commit -m "chore: update branches.json from tidb" || echo "No changes to commit"
          git push
